#msg21xx touchpanel driver
# modify(add) by junfeng.zhou.sz for [TP driver development (1st source)] with PR721418 begin
obj-$(CONFIG_TOUCHSCREEN_MSG21XX_PSENSOR) += msg2138.o
obj-$(CONFIG_TOUCHSCREEN_MSG21XX_PSENSOR) += msg_psensor_drv.o
# modify(add) by junfeng.zhou.sz for [TP driver development (1st source)] with PR721418 end
