/* Copyright Statement:
*This firmware are protected under relevant copyright laws,this information contained
*herein is confidential and proprietary to Goodix.
*
*GOODIX (C) 2013. All rights reserved.
*
*WARNING:The GTP_COMPATIBLE_MODE part of this file was generated by the specialized tools,
*please do not modify it manually!
*
*/


#ifndef _GT9XX_FIRMWARE_H_
#define _GT9XX_FIRMWARE_H_

#if GTP_HEADER_FW_UPDATE
unsigned char gtp_default_FW[] = 
{
            //TODO:Puts your update firmware data here!
//#include "GT9157_1078_BEAF.BIN"
#include "GT9157_1079_EE9A.h"
#ifdef CONFIG_TCT_8X26_M812_CMCC
#include "GT9158_1040(AA2B)_M812_cmcc.hex"
#endif
};
#endif

/*
*[HW INFO]00900600
*[PID]910
*[VID]1010
*[GENERATED]2013/08/27 20:59:13
*/
#if GTP_COMPATIBLE_MODE
unsigned char gtp_default_FW_fl[] = {
};
#endif

#endif
